version: "2"
services:
  comments:
    build: .
    # image: alaahussein94/starkloud-comments
    ports:
      - "9003:9003"
    depends_on:
      - db
    working_dir: /dockerFolder
    environment:
      SEQ_DB: commentsdb
      SEQ_USER: postgres
      PORT: 9003
      DATABASE_URL: postgres://postgres@db:5432/commentsdb
  # web:
  #   image: footerplayer
  #   command: node database/helper.js
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=commentsdb
